### ISSUE TITLE
Feature request: multiple translator is english word is both noun and verb

### ISSUE THREAD

**Issue by ePascalC** [Mte90/GlotDict#11]
Taking the english word 'archive' as an example, this would become 'archivio' as noun and 'archiviare' as a verb in Italian. So the same English word would exist on 2 different rows.

- How would the json file need to be changed ? Just add an extra field for each translation called 'PartOfSpeech'? Or would you use the 'pos' field that is currently unused (I think) ?
- How to change the display ? I would go for 'archivio (noun), archiviare (verb)'
- How to read more than one translation from the json file?

Thanks, Pascal.

**Comment by Mte90** [comment]
Good point!
In that case I think that we have to study how to improve the glossary in the way that there is a terms with different explanations in the comment field.
Pos actually is not used because glotpress not use that parameter, and read more than one translation I had to improve the extension but I think that can be difficult to manage.
Also the JSON if found multiple object that use the same name, in that case archive, they ignore everyone excerpt the first so we need to improve the JSON file itself.

**Comment by ePascalC** [comment]
So to make it easy for you, we would just need to change the json file ?

From:
    "archive": {
        "comment": "",
        "pos": "",
        "translation": "archivio"
    }

To:
    "archive": {
        "comment": "Noun: Mai il neologismo depositare, Verb: nota sul verb ",
        "pos": "",
        "translation": "archivio (noun), archiviare (verb)"
    }

?
How could I get it onto 2 lines ? Adding <br /> ?

**Comment by Mte90** [comment]
No br,
in that case is better to improve the glossary itself because the json is auto generated.
