### ISSUE TITLE
Add layover during the load of the extension in the page

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#110]
Browser: All
Link: Any
Locale used: Any

Hi @Mte90,

I only mention this as I'd now done this a couple times... But with the delay of the action button column being injected to the right of the column with 'Details' links I keep finding myself going to click Details and while clicking the action buttons suddenly appear so I hit them instead by accident.  Because of the delayed load of those actions could we have them injected to the left of the 'Details' link column rather than to the right, that way the 'Details' links don't move after the JS fires so there's no accidental clicking. When moved to GlotPress and run via PHP this won't be an issue as they'll be present from load.

Hope that makes sense,

Cheers

**Comment by Mte90** [comment]
So the page is loaded you click on details and in the meantime is loading all the buttons but instead click on details you click on the buttons of glotdict in the column.
Uhm I can add a black fade in all the window to avoid this type of clicking but usually I double click on the row instead of details to open the string.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90, that's exactly it. I can probably use the double-click method as well, I'm just so used to hitting the Details link
