### ISSUE TITLE
Support Grammarly or similar for basic spelling/grammar flags

### ISSUE THREAD

**Issue by garrett-eclipse** [Mte90/GlotDict#204]
It would be nice to provide an integration to Grammarly or another spell checking service in order to flag basic spelling and grammar issues to translators.

**Comment by Mte90** [comment]
I am personally a fan of languagetool.org that is a open source alternative and using it in the browser.
Anyway this services have a limit for requests so probably for a localizer can be a problem because will happen for every request.
I think that we can investigate it anyway but probably the problems with this services is that they don't follow the glossary of the community.

**Comment by garrett-eclipse** [comment]
Thanks @Mte90 
I agree it's probably not worth the effort due to those limitations especially when there's existing tools with large teams backing them like LanguageTool and Grammarly. As such I provided links to them as recommendations.
Also added security to external links.

**Comment by garrett-eclipse** [comment]
Closing as wontfix, but addressed with links to Grammarly and LanguageTool to assist users.
