### ISSUE TITLE
URL Glossary terms not marked on collapsed row

### ISSUE THREAD

**Issue by garretthyder** [Mte90/GlotDict#240]
See screen to illustrate;
<img width="545" alt="Screen Shot 2019-07-08 at 12 36 19 PM" src="https://user-images.githubusercontent.com/8726005/60837557-4a3ce700-a17d-11e9-85db-e83fbaff38f3.png">

The first row should be marked with the blue 'Glossary' border as it contains the wordpress.org term. If you open it's highlighted just not seeing the blue border when the row is collapsed.

Might have something to do with it's within a link.

**Comment by vlad-timotei** [comment]
Since this issue has been created, GP itself changed some things too.
This feature has been broken in GD since this [changeset ](https://meta.trac.wordpress.org/changeset/11051) and then fixed in #297 

Not having a URL to test if this issue is still present is a bit difficult. 
So, is this still a bug? And if so, where can we see it live?
If not, I propose to close this.
