### ISSUE TITLE
Regression issue : the next editor is not opened when a translation is changed

### ISSUE THREAD

**Issue by ajoah** [Mte90/GlotDict#276]
Hi,

there is a regression issue with this commit : https://github.com/Mte90/GlotDict/commit/0c2b64d7017d2088602254f13d6aa8ba5d3f019d (https://github.com/Mte90/GlotDict/pull/259) by @webaxones 

The commit permits to not open the next editor when you click on Approve, Fuzzy, Reject next to the preview row. (Great feature :)) 
The commit keeps next editor open if a new translation is added but it doesn't do the same thing when you change a translation.

When you change an existing translation, after click on save button (or CTRL+enter) : 
- Before commit: the next editor opens.
- After commit: the next editor remains closed

Not pratictal when you review old translations of a plugin ^^.

It is due to this line : https://github.com/webaxones/GlotDict/blob/87f1ccf210c3367e1ff3a499e6900915dcb54df6/js/glotdict-functions.js#L284

Indeed, when you change a translation `!mutation.previousSibling.matches('.editor.untranslated')` is always true. It works only for a new translation.

I don't know if is it possible to fix this issue with mutation observer because there is no difference between classes when you change a translation and when you approve.

Example : 
- after saving the translation (CTRL + ENTER), the editor of "This user has not made any comments." should have opened.
![glotdict](https://user-images.githubusercontent.com/10757301/127647684-875644e4-ce3c-438f-843f-d0842d1a2aec.gif)

Maybe there is another problem: if you click on Approve, Fuzzy, Reject buttons when the editor is opened, you expect that the next editor opens no ? I think we have to differentiate a click on the actions buttons next to the preview row and the buttons next to the editor.

**Comment by vlad-timotei** [comment]
Hi! 
I ran into this issue as well.

Expected behavior:
- additional GlotDict buttons don't open an editor (current state)
- default GlotPress buttons open the next editor (default GP beahvior) (not happening)

> I don't know if is it possible to fix this issue with mutation observer because there is no difference between classes when you change a translation and when you approve.

Indeed this is an issue. I have an idea, it works, but maybe some of you can take this initial idea and make it better. 
The idea is to add a variable named open_next_editor that is set to _true_  by default and to _false_ for 500ms after a custom GD button is clicked. (500ms should be enough for the saving process to happen). Then we check open_next_editor state before either hiding (gd_auto_hide_next_editor) or showing (hook to GP $gp.editor.next) the next editor. 

So:
1. A global variable 
```
var open_next_editor = true;
```
2. [Here](https://github.com/webaxones/GlotDict/blob/f91d18f97c4ea0b89b82016b85d51003c9548cf9/js/glotdict-column.js#L32), when a custom GD button is clicked, it is set to false:
```
open_next_editor = false;
setTimeout( function(){ open_next_editor = true; }, 500 );
```
3. Check its state
- Option A: Alter [this line](https://github.com/webaxones/GlotDict/blob/f91d18f97c4ea0b89b82016b85d51003c9548cf9/js/glotdict-functions.js#L393) to check for state of open_next_editor (not tested)
- Option B: Add a hook to  $gp.editor.next to instead of gd_auto_hide_next_editor(); (tested, works, but I don't know how you feel about altering $gp.editor.next)
```
$gp.editor.next = ( function( original ) {
  return function() {
    if( open_next_editor ){
      original.apply( $gp.editor, arguments );
    }
  }
})( $gp.editor.next );

```
The above method implemented, exemplifying the different behavior between GlotPress buttons and Glot Dict buttons. 

![new_GlotDict](https://user-images.githubusercontent.com/65488419/127661359-edf7ae61-2ea6-48a3-a27b-3a105e6858eb.gif)

What do you think?

**Comment by ajoah** [comment]
I have tested the @webaxones patch and it works very well ! :) thank you
