### ISSUE TITLE
Same shortcut for 2 actions

### ISSUE THREAD

**Issue by webaxones** [Mte90/GlotDict#291]
Browser: Chrome, Firefox
Link: [here](https://github.com/Mte90/GlotDict/blob/master/js/glotdict-hotkey.js#L64) and [here](https://github.com/Mte90/GlotDict/blob/master/js/glotdict-hotkey.js#L94)
Locale used: whatever you want

Same shortcut is used for 2 different things: Reject a string and Reset all settings…
As I refactor a function of the settings (where the line about the shortcut is also to be corrected), I affect to myself this issue that I will deal with after.
But I accept any idea about the shortcut to add for the settings reset :)

**Comment by vlad-timotei** [comment]
The issue is a bit deeper. 

Settings screen states that `Ctrl+Shift+R` reset all GlotDict settings. But that is not true. 

The only ones being reset are the "invisible settings": 
https://github.com/Mte90/GlotDict/blob/bc2cf68df6d8c97560258d2f6f17cca03f8b39fb/js/glotdict-hotkey.js#L94-L98
What about others? Those need to be reset as well!

In addition to the above, we need to reset: 
```
gd_no_non_breaking_space
gd_autosubmit_bulk_copy_from_original 
gd_no_final_dot  
gd_no_initial_space
gd_force_autosubmit_bulk_copy_from_original
gd_curly_apostrophe_warning
gd_localized_quote_warning
gd_no_final_other_dots
gd_no_initial_uppercase
gd_no_trailing_space
gd_no_glossary_term_check
```



As for the new shortcut for the settings reset, I suggest:` Alt+Shift+R`


As for this shortcut being the same for both actions, based on my tests, unfortunately, it fires both actions (Rejection and Reset), but fortunately, it only resets those three options, not all options - so it is a partly contained bug, but needs a fix.

**Comment by webaxones** [comment]
In fact, I find that having a shortcut to reset all settings is quite dangerous. It's so easy to make a keyboard error.
Wouldn't it be better to remove this shortcut, and maybe later add a real setting with no shortcut and a with a confirmation message to click on?

**Comment by vlad-timotei** [comment]
I agree the `Reset all settings` action would be much more suitable as a button on the Settings page with a confirmation message. It is not an often action so it doesn't need a hotkey, IMHO.
