### ISSUE TITLE
Glossary check validates derivated translations when it shouldn't

### ISSUE THREAD

**Issue by NekoJonez** [Mte90/GlotDict#352]
So, there is a problem with the warnings in nl_NL & nl_BE. 

The thing is, the terms "site" and "website" we translate differently. 

In nl_NL, we use: "site" 
In nl_BE, we use: "website"

And here comes the issue. Since Glotdict sees the word "site" in "website"... It gets accepted in nl_NL even when website needs to be shortend to site.

**Comment by vlad-timotei** [comment]
This is a GlotDict issue, as it reffers to GD not generating the correct error.
Here's why:

We have the `abc` original and `xyz` as Glossary official translation.

In most of the cases, `xyz` needs to be derived (articulated form, plural form, any other form). This should not generate a warning. To do so, GD only checks if `xyz` is present in the translation, so `123xyz456` would still be valid, since it's a derivation. 

I understand this kind of checking things does not suit your workflow in this locale, but if we were to change things, for example to check for ` xyz ` (note the start and end space), this would generate a lot of false positive warnings for derived forms.

This is how I see things and for now I personally don't see a solution, but it's something to look into.

**Comment by NekoJonez** [comment]
Excellent. I think you can use one or two strings of the other issue I made since it has examples that can count for this ticket as well. (The one where if you change just one word to the correct translation, you can save it, I gave examples there where you have "website" and "site".)

**Comment by psmits1567** [comment]
Currently it is warning you if it does not find the glossary verb in a combined string.
For me that is annoying because for the locale nl_NL the word is perfectly translated.
In your example website, we have site in locale NL glossary. So if it finds the word "site" in a combined word, it should warn.
But there are other word combinations that are a combination of two words, where the last one is a proper translated word
In that case it should not warn you. Maybe add a local list for word combinations that should not create a warning??
Otherwise you cannot solve this in my opinion

**Comment by Mte90** [comment]
The glossary check as today is done by GlotPress since few years and not anymore by Glotdict itself.

**Comment by psmits1567** [comment]
Ok it that case, this issue can be closed I think
We need to address it in GlotPress
