### ISSUE TITLE
Manifest version 2 is deprecated

### ISSUE THREAD

**Issue by nilovelez** [Mte90/GlotDict#413]
Chrome extension manager has started to complain about v2 manisfest:

> Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

Browser: Chrome
Link: Chrome extensions console
Locale used: n/a

**Comment by vlad-timotei** [comment]
Hi @nilovelez 
Thank you for the issue!
Are you using the version from the Chrome Web Store? The published version uses Manifest V3.
That is because in the package generator code we do that for Chrome package only.

See this https://github.com/Mte90/GlotDict/pull/401

If you're using the repository code locally and you want a fix just for you, you could take a look at the previous PR
https://github.com/Mte90/GlotDict/pull/400 that was proposing to have 2 manifests - one for Chrome and one for Firefox, but that was a bit too complicated to maintain.

I'm closing this issue, but you think there is something to fix, let us know. Thank you!

**Comment by nilovelez** [comment]
Yes, I tested it locally from a repo clone I made for working on the CSS styles.

If it's taken care of in the release package, there isn't anything more to do, thanks for the reply.
