### ISSUE TITLE
Experiment for plural forms in the glossaries

### ISSUE THREAD

**Issue by Mte90** [Mte90/GlotDict#60]

**Comment by deshack** [comment]
English regular plurals rules are:

* **General rule:** append letter *s*
* **Nouns that end in *ch*, *x*, *s*, *z*, or *s-like* sounds** require an *es* for the plural (here the problem is to match *s-like* sounds)
* **Nouns that end in a vowel + *y*** take the letter *s*
* **Nouns that end in a consonant + *y*** drop the *y* and take *ies*
* ***A lot of* nouns that end in *o*** take *es* in the plural (and here the problem is *a lot*)
* **Nouns that end in *f* or *fe*** *usually* change the *f* sound to *v* sound and add *s* or *es* (oh shit!)

And then there are irregular plurals...

[Reference and examples](http://www.myenglishpages.com/site_php_files/grammar-lesson-plurals.php)

May we support some plural forms (the most regular ones) and require other ones (irregular ones, first of all) to be added to the glossary?

**Comment by Mte90** [comment]
I find this http://stackoverflow.com/questions/27194359/javascript-pluralize-a-string i can try to integrating with semplifying

**Comment by Mte90** [comment]
The pluralize.js library do the dirt job and now it's integrated.
